<?php

namespace LostThings\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends EntityRepository
{
    public function getAreaById($id){
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM LostThingsAdminBundle:Area a WHERE a.cityId = :id')
            ->setParameter('id', $id)
            ->getArrayResult();
    }
}
