<?php

namespace LostThings\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    public function getCityById($id){
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM LostThingsAdminBundle:City c WHERE c.countryId = :id ORDER BY c.city')
            ->setParameter('id', $id)
            ->getArrayResult();
    }
}
