<?php

namespace LostThings\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FindRepository extends EntityRepository
{
    public function findAllFindThings($ids){
        return $this->getEntityManager()
            ->createQuery('SELECT f FROM LostThingsAdminBundle:Find f WHERE f.id IN (:ids) ORDER BY f.dateFind DESC')
            ->setParameters(array('ids' => $ids))
            ->getResult();
    }


    public function findAllFindThingsArray($ids){
        return $this->getEntityManager()
            ->createQuery('SELECT f FROM LostThingsAdminBundle:Find f WHERE f.id IN (:ids) ORDER BY f.dateFind DESC')
            ->setParameters(array('ids' => $ids))
            ->getArrayResult();
    }
}
