<?php

namespace LostThings\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LostRepository extends EntityRepository
{
    public function findAllLostThings($ids){
        return $this->getEntityManager()
            ->createQuery('SELECT l FROM LostThingsAdminBundle:Lost l WHERE l.id IN (:ids)')
            ->setParameters(array('ids' => $ids))
            ->getResult();
    }

    public function findAllLostThingsArray($ids){
        return $this->getEntityManager()
            ->createQuery('SELECT l FROM LostThingsAdminBundle:Lost f WHERE l.id IN (:ids)')
            ->setParameters(array('ids' => $ids))
            ->getArrayResult();
    }
}
