<?php

namespace LostThings\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function findSend($user){
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM LostThingsAdminBundle:Message c WHERE c.sendUserId = :user GROUP BY c.receivedUserId')
            ->setParameter('user', $user)
            ->getResult();
    }

    public function findReceived($user){
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM LostThingsAdminBundle:Message c WHERE c.receivedUserId = :user')
            ->setParameter('user', $user)
            ->getResult();
    }


    public function findMessages($received_user_id, $send_user_id){
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM LostThingsAdminBundle:Message r
                            WHERE r.sendUserId = :sendUserId
                              AND r.receivedUserId = :receivedUserId
                                OR r.sendUserId = :receivedUserId
                                  AND r.receivedUserId = :sendUserId
                                    ORDER BY r.createdAt')
            ->setParameter('receivedUserId', $received_user_id)
            ->setParameter('sendUserId', $send_user_id)
            ->getResult();
    }

    public function findMessagesArray($received_user_id, $send_user_id){
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM LostThingsAdminBundle:Message r
                            WHERE r.sendUserId = :sendUserId
                              AND r.receivedUserId = :receivedUserId
                                OR r.sendUserId = :receivedUserId
                                  AND r.receivedUserId = :sendUserId
                                    ORDER BY r.createdAt')
            ->setParameter('receivedUserId', $received_user_id)
            ->setParameter('sendUserId', $send_user_id)
            ->getArrayResult();
    }

    public function dontReadMessage($user_id){
        return $this->getEntityManager()
            ->createQuery('SELECT m FROM LostThingsAdminBundle:Message m WHERE m.receivedUserId = :sendUserId AND m.status = 0 ORDER BY m.createdAt DESC')
            ->setParameter('sendUserId', $user_id)
            ->getResult();
    }
}
