<?php

namespace LostThings\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StreetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreetRepository extends EntityRepository
{
    public function getStreetById($id){
        return $this->getEntityManager()
            ->createQuery('SELECT s FROM LostThingsAdminBundle:Street s')
            ->getArrayResult();
    }
}
