<?php

namespace LostThings\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StreetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreetRepository extends EntityRepository
{

    public function search($search){
        return $this->getEntityManager()
            ->createQuery("SELECT s FROM LostThingsAdminBundle:Street s WHERE s.street LIKE :search ")
            ->setParameter('search', "%$search%")
            ->getResult();
    }

    public function getStreetById($city_id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT DISTINCT s.street FROM LostThingsAdminBundle:Street s WHERE s.cityId = :cityId')
            ->setParameter('cityId', $city_id)
            ->getArrayResult();
    }
}