<?php

namespace LostThings\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ThingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThingRepository extends EntityRepository
{


    public function search($search){
        return $this->getEntityManager()
            ->createQuery("SELECT t FROM LostThingsAdminBundle:Thing t WHERE t.nameThing LIKE :search ")
            ->setParameter('search', "%$search%")
            ->getResult();
    }

    public function getBaseThing(){
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM LostThingsAdminBundle:Thing t GROUP BY t.nameThing')
            ->getArrayResult();
    }
}
