<?php

namespace LostThings\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{


    public function search($search){
        return $this->getEntityManager()
            ->createQuery("SELECT u FROM LostThingsAdminBundle:User u WHERE u.username LIKE :search OR u.email LIKE :search")
            ->setParameter('search', "%$search%")
            ->getResult();
    }
}
