main:
    path:     /
    defaults: { _controller: LostThingsMainBundle:Index:index }

find:
    path:     /find/
    defaults: { _controller: LostThingsMainBundle:Find:index }


find_get_city:
    path: /find/getcity/
    defaults: { _controller: LostThingsMainBundle:Find:getCity }

find_get_area:
    path: /find/getarea/
    defaults: { _controller: LostThingsMainBundle:Find:getArea }

find_get_street:
    path: /find/getstreet/
    defaults: { _controller: LostThingsMainBundle:Find:getStreet }

find_get_thing:
    path: /find/getthing/
    defaults: { _controller: LostThingsMainBundle:Find:getThing }

save_find_thing:
    path: /find/save_find_thing/
    defaults: { _controller: LostThingsMainBundle:Find:saveFindThing}

lost:
    path:     /lost/
    defaults: { _controller: LostThingsMainBundle:Lost:index }

save_lost_thing:
    path: /find/save_lost_thing/
    defaults: { _controller: LostThingsMainBundle:Lost:saveLostThing}


search_find:
    path: /find/search/{id}/
    defaults: { _controller: LostThingsMainBundle:Search:resultsSearchFind }


search_lost:
    path: /lost/search/{id}/
    defaults: { _controller: LostThingsMainBundle:Search:resultsSearchLost }



personal_area:
    path: /personal-area/
    defaults: { _controller: LostThingsMainBundle:PersonalArea:index }

personal_area_lost_search:
    path: /personal-area/lost/search/{id}
    defaults: { _controller: LostThingsMainBundle:Search:personalAreaResultSearchLost }

personal_area_find_search:
    path: /personal-area/find/search/{id}
    defaults: { _controller: LostThingsMainBundle:Search:personalAreaResultSearchFind }

personal_area_thing_delete_lost:
    path: /personal-area/delete-lost/{id}
    defaults: { _controller: LostThingsMainBundle:PersonalArea:deleteLost }

personal_area_thing_delete_find:
    path: /personal-area/delete-find/{id}
    defaults: { _controller: LostThingsMainBundle:PersonalArea:deleteFind }

paersonal_area_refresh_lost:
    path: /personal-area/refresh-lost/{id}
    defaults: { _controller: LostThingsMainBundle:Search:countLostMatches }


paersonal_area_refresh_find:
    path: /personal-area/refresh-find/{id}
    defaults: { _controller: LostThingsMainBundle:Search:countFindMatches }


private_message:
    path: /private-message/
    defaults: { _controller: LostThingsMainBundle:PrivateMessage:message }

correspondence:
    path: /personal-area/correspondence/{received_user_id}
    defaults: { _controller: LostThingsMainBundle:PrivateMessage:correspondence }